// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package config

import (
	"fmt"
	"strings"
)

const (
	// ScheduleActionBlockGroups is a ScheduleAction of type BlockGroups.
	// Add specified groups to blocking check during window
	ScheduleActionBlockGroups ScheduleAction = iota
	// ScheduleActionBlockAll is a ScheduleAction of type BlockAll.
	// Block ALL DNS requests during window (returns NXDOMAIN)
	ScheduleActionBlockAll
	// ScheduleActionAllowGroupsOnly is a ScheduleAction of type AllowGroupsOnly.
	// Only allow domains matching specified allowlist groups; block everything else
	ScheduleActionAllowGroupsOnly
)

var ErrInvalidScheduleAction = fmt.Errorf("not a valid ScheduleAction, try [%s]", strings.Join(_ScheduleActionNames, ", "))

const _ScheduleActionName = "blockGroupsblockAllallowGroupsOnly"

var _ScheduleActionNames = []string{
	_ScheduleActionName[0:11],
	_ScheduleActionName[11:19],
	_ScheduleActionName[19:34],
}

// ScheduleActionNames returns a list of possible string values of ScheduleAction.
func ScheduleActionNames() []string {
	tmp := make([]string, len(_ScheduleActionNames))
	copy(tmp, _ScheduleActionNames)
	return tmp
}

// ScheduleActionValues returns a list of the values for ScheduleAction
func ScheduleActionValues() []ScheduleAction {
	return []ScheduleAction{
		ScheduleActionBlockGroups,
		ScheduleActionBlockAll,
		ScheduleActionAllowGroupsOnly,
	}
}

var _ScheduleActionMap = map[ScheduleAction]string{
	ScheduleActionBlockGroups:     _ScheduleActionName[0:11],
	ScheduleActionBlockAll:        _ScheduleActionName[11:19],
	ScheduleActionAllowGroupsOnly: _ScheduleActionName[19:34],
}

// String implements the Stringer interface.
func (x ScheduleAction) String() string {
	if str, ok := _ScheduleActionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ScheduleAction(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ScheduleAction) IsValid() bool {
	_, ok := _ScheduleActionMap[x]
	return ok
}

var _ScheduleActionValue = map[string]ScheduleAction{
	_ScheduleActionName[0:11]:  ScheduleActionBlockGroups,
	_ScheduleActionName[11:19]: ScheduleActionBlockAll,
	_ScheduleActionName[19:34]: ScheduleActionAllowGroupsOnly,
}

// ParseScheduleAction attempts to convert a string to a ScheduleAction.
func ParseScheduleAction(name string) (ScheduleAction, error) {
	if x, ok := _ScheduleActionValue[name]; ok {
		return x, nil
	}
	return ScheduleAction(0), fmt.Errorf("%s is %w", name, ErrInvalidScheduleAction)
}

// MarshalText implements the text marshaller method.
func (x ScheduleAction) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ScheduleAction) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseScheduleAction(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ScheduleAction) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
